# Generated by Django 4.1.6 on 2023-02-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberBoard',
        ),
    ]
