# Generated by Django 4.1.6 on 2023-02-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('board', '0003_alter_board_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardUser', to='auth.group'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
