# Generated by Django 4.1.6 on 2023-02-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_board_user_remove_task_assigned_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='group',
        ),
    ]
