# Generated by Django 4.1.6 on 2023-02-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('board', '0005_rename_user_board_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
