# Generated by Django 4.1.6 on 2023-02-13 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0007_task_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
