# Generated by Django 4.1.6 on 2023-02-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_board_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_at',
        ),
    ]
